### ISSUE TITLE
Master data not generated when running with postgres

### ISSUE THREAD

**Issue by rajagopalanrg** [ybkuroki/go-webapp-sample#243]
## Summary
> The application is connecting with my postgres server but not creating the master data

## Cause
> Why such a problem happened?

### To reproduce
Changed the application.docker.yml file and added the following config
database:
  dialect: postgres
  host: localhost
  port: 5432
  dbname: testdb
  username: admin
  password: psltest
  migration: true

Then I built the application go build main.go
Execute the app with ./main.exe -env=docker
The output is 
PS C:\Users\Raja.Ramanujam\OneDrive - Neudesic\Documents\kube-monitoring\golangapp\go-webapp-sample> .\main.exe -env=docker
2022-11-08T18:27:39.688+0530    INFO    logger/logger.go:62     Success to read zap logger configuration: zaplogger.docker.yml
2022-11-08T18:27:39.689+0530    INFO    go-webapp-sample/main.go:41     Loaded this configuration : application.docker.yml
2022-11-08T18:27:39.689+0530    INFO    repository/repository.go:50     Try database connection
2022-11-08T18:27:42.186+0530    INFO    repository/repository.go:56     Success database connection, localhost:5432

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.9.0
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:8080

## Expected behavior
The master data is not generated as how it use to do when using the application.develop.yml file
PS C:\Users\Raja.Ramanujam\OneDrive - Neudesic\Documents\kube-monitoring\golangapp\go-webapp-sample> .\main.exe
2022-11-08T18:16:40.591+0530    INFO    logger/logger.go:62     Success to read zap logger configuration: zaplogger.develop.yml
2022-11-08T18:16:40.592+0530    INFO    go-webapp-sample/main.go:41     Loaded this configuration : application.develop.yml
2022-11-08T18:16:40.593+0530    INFO    repository/repository.go:50     Try database connection
2022-11-08T18:16:40.611+0530    INFO    repository/repository.go:56     Success database connection, book.db:
2022-11-08T18:16:40.629+0530    DEBUG   logger/gormlogger.go:58 [gorm] INSERT INTO `authority_master` (`name`) VALUES ("Admin") RETURNING `id`
2022-11-08T18:16:40.700+0530    DEBUG   logger/gormlogger.go:58 [gorm] INSERT INTO `account_master` (`name`,`password`,`authority_id`) VALUES ("test","$2a$10$TiX8wtNwK6QgnRQnfSkxvuBstQcteN0NcCdW7fDT3XyNpjJnVhqme",2) RETURNING `id`
2022-11-08T18:16:40.766+0530    DEBUG   logger/gormlogger.go:58 [gorm] INSERT INTO `account_master` (`name`,`password`,`authority_id`) VALUES ("test2","$2a$10$Py4EzSdPWU6w0uECT8KXRud5wWWGLWDaHHv7wzwCayqV0tSOOhN5e",2) RETURNING `id`
2022-11-08T18:16:40.772+0530    DEBUG   logger/gormlogger.go:58 [gorm] INSERT INTO `category_master` (`name`) VALUES ("Technical Book") RETURNING `id`
2022-11-08T18:16:40.780+0530    DEBUG   logger/gormlogger.go:58 [gorm] INSERT INTO `category_master` (`name`) VALUES ("Magazine") RETURNING `id`
2022-11-08T18:16:40.787+0530    DEBUG   logger/gormlogger.go:58 [gorm] INSERT INTO `category_master` (`name`) VALUES ("Novel") RETURNING `id`       
2022-11-08T18:16:40.795+0530    DEBUG   logger/gormlogger.go:58 [gorm] INSERT INTO `format_master` (`name`) VALUES ("Paper Book") RETURNING `id`
2022-11-08T18:16:40.869+0530    INFO    middleware/middleware.go:132    Served the static contents.

## How to deal with this issue
> How do you fix it?

**Comment by ybkuroki** [comment]
@rajagopalanrg 
Is `extension.master_generator` set true in your `application.yml`?

https://github.com/ybkuroki/go-webapp-sample/blob/master/application.develop.yml#L11

**Comment by rajagopalanrg** [comment]
yes, I set it to true but not working

**Comment by ybkuroki** [comment]
@rajagopalanrg 
This application haven't especially controled for the master data generator when the running parameter is -env=docker.

As long as I see your log, it seems that your settings is mistaken is cause.
Is the contents of `application.docker.yml` the following?

```yml
database:
  dialect: postgres
  host: localhost
  port: 5432
  dbname: testdb
  username: admin
  password: psltest
  migration: true

extension:
  master_generator: true   # << CHECK THIS PARAMETER!!!   
  cors_enabled: false
  security_enabled: true

log: request_log_format: ${remote_ip} ${account_name} ${uri} ${method} ${status} 

security:
  auth_path:
    - /api/.*
  exclude_path:
    - /swagger/.*
    - /api/auth/login$
    - /api/auth/logout$
    - /api/health$ 
  user_path:
    - /api/.*
  admin_path:
    - /api/.*
```

Also, have the database schema already created?
